#file: noinspection ComposeUnknownValues

services:
    redpanda:
        image: redpandadata/redpanda:v26.2.3
        profiles: [auth]
        command:
            - redpanda
            - start
            - --mode=dev-container
            - --smp=1
            - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
            - --advertise-kafka-addr=internal://redpanda:9092,external://127.0.0.1:${REDPANDA_PORT:?}
            - --rpc-addr=redpanda:33145
            - --advertise-rpc-addr=redpanda:33145
        ports:
            - "${REDPANDA_PORT:?}:19092"
        volumes:
            - redpanda-data:/var/lib/redpanda/data
        networks: [marketplace]
        healthcheck:
            test: ["CMD-SHELL", "rpk cluster health"]
            interval: 5s
            timeout: 3s
            retries: 10
            start_period: 10s
            start_interval: 1s
        restart: unless-stopped

    redpanda-console:
        image: redpandadata/console:v3.12.0
        profiles: [auth]
        environment:
            KAFKA_BROKERS: redpanda:9092
        ports:
            - "${REDPANDA_CONSOLE_PORT:?}:8080"
        networks: [marketplace]
        depends_on:
            redpanda:
                condition: service_healthy
        restart: unless-stopped

volumes:
    redpanda-data: